pages:
  image: asciidoctor/docker-asciidoctor
  tags:
    - docker-pages
  stage: deploy
  script:
    - asciidoctor -r asciidoctor-diagram HOWTO.adoc
    - mkdir public
    - cp HOWTO.html public/index.html
  artifacts:
    paths:
      - public
  only:
    - master
