= How to add a new activity rule

== 🛠 Pre-requesite

The rule configuration already exists.
You can check with the following API :

Exchange:: `cutadmin`
RoutingKey:: `production-rules-configuration.query.get`

== 💻 Server

* Add your activity in the record with the corresponding id (lowercase with dash instead of space)
[source, typescript]
----
include::server/src/interface/resources/ActivitiesMapping.ts[tags=mapping]
---- 

That's all 😎

== 🕸 Client

=== Create a new file `XXXRule.tsx` in `src/rules`

* Define a model `XXX` for statement result of the rule

.Example for existing `Sequencing`
[source, typescript]
----
export interface Sequencing extends StatementResult {
  splitList: boolean;
  firstSubListSize: number;
}
----

* Create a `React` component `XXXRule` using common hooks ( `useRule`,  `useRuleValidator`)

=== Declare rule in UIState

In the file `src/UIState.tsx`

* Declare a new key in `UIState` type : `'xxx'?: ActivityRule<XXX>`

[source, typescript]
----
include::client/src/UIState.tsx[tags=uiState]
----

* Declare a new action : `UpdateStatementResult<'xxx', XXX>`

[source]
----
include::client/src/UIState.tsx[tags=action]
----

=== Declare route in router

In the file `src/ProductionProcessScreen.tsx`

* declare a new route 

[source, jsx]
----
 <Route exact path="/xxx" component={XXXRule} />
----

== 🙈 LTF Test

Add a new functional test for the rule in `ltf/src/test/tlf/com/lectra/functional`

== Online Help

Retrieve the path of  the help in the project #CuttingRoom/CutPreparation.Applications/-/tree/master/SystemManager/Tooltips/EN/Content/02-Processus-Production#

In the project #cloud\online-help#, update the file `alias.json` to add an alias with the path on the online help

  "PP_CUTTING_ACTIVITY": "Content/02-Processus-Production/14-Activite-Decoupe/Activite-Decoupe.htm",

And use this alias in the form of the rule

  const urls = useHelpUrls('PP_CUTTING_ACTIVITY');



