PORT: "8080"
AUTH_DOMAIN: "login.mylectra.com"
AUTH_CLIENT_ID: "0kh1GgVEZx5JfZxIwQAZGsKjcQzTTKhz"
AUTH_AUDIENCE: "https://gateway-cuttingroom.mylectra.com"
FF_CLIENT_ID: "5c61464129126734be86aca5"
RABBITMQ_HOST: "amqps.cloudservices.mylectra.com"
RABBITMQ_VHOST: "common-prod"
RABBITMQ_PORT: "443"
RABBITMQ_USER: "cutting-room-production-process-bot"
RABBITMQ_SSL: "true"
HELP_URI: "https://help.mylectra.com/help/systemmanager"