const {
  RABBITMQ_HOST,
  RABBITMQ_PORT,
  RABBITMQ_USER,
  RABBITMQ_VHOST,
  RABBITMQ_PASSWORD,
  RABBITMQ_SSL
} = process.env;
export const RABBITMQ_URL = `${RABBITMQ_SSL === "true" ? "amqps" : "amqp"}://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/${RABBITMQ_VHOST}`;
