apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:  
  name: {{.Release.Name}}
  labels:
    app: {{.Chart.Name}}
    release: {{.Release.Name}}
    maintainer: {{.Values.maintainer}}
spec:
  maxUnavailable: {{.Values.maxUnavailable}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
      release: {{.Release.Name}}
      maintainer: {{.Values.maintainer}}
