apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Release.Name}}
  labels:
    app: {{.Chart.Name}}
    release: {{.Release.Name}}
    maintainer: {{.Values.maintainer}}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - {{.Values.dnsPrefix}}{{if ne .Values.Env "prod"}}.{{.Values.Env}}{{end}}.mylectra.com
      secretName: {{.Release.Name}}-tls
  rules:
  - host: {{.Values.dnsPrefix}}{{if ne .Values.Env "prod"}}.{{.Values.Env}}{{end}}.mylectra.com
    http:
      paths:
        - backend:
            serviceName: {{.Release.Name}}
            servicePort: 80
          path: /
