apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{.Release.Name}}
spec:
  minAvailable: {{.Values.minAvailable}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
      release: {{.Release.Name}}
      maintainer: {{.Values.maintainer}}
